{"uid":"92bd690e5a51d28b","name":"a1-valves.com заказать звонок -- @1.1 ","fullName":"Проверка сайта a1-valves.com: a1-valves.com заказать звонок","historyId":"7faf572cfcca69d732baa5f93ff54721","time":{"start":1671072142855,"stop":1671072405256,"duration":262401},"status":"broken","statusMessage":"selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_TIMED_OUT\n  (Session info: headless chrome=108.0.5359.94)\n\n","statusTrace":"  File \"/opt/hostedtoolcache/Python/3.9.15/x64/lib/python3.9/site-packages/behave/model.py\", line 1812, in run\n    match.run(runner.context)\n  File \"/opt/hostedtoolcache/Python/3.9.15/x64/lib/python3.9/site-packages/behave/matchers.py\", line 97, in run\n    self.func(context, *args, **kwargs)\n  File \"features/steps/basic_steps.py\", line 86, in open_page\n    open_url(context, page_name)\n  File \"features/steps/basic_steps.py\", line 80, in open_url\n    context.driver.get(url) if url.startswith('http') else context.driver.get(f'https://{url}')\n  File \"/opt/hostedtoolcache/Python/3.9.15/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py\", line 333, in get\n    self.execute(Command.GET, {'url': url})\n  File \"/opt/hostedtoolcache/Python/3.9.15/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"/opt/hostedtoolcache/Python/3.9.15/x64/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n","flaky":false,"newFailed":false,"newBroken":true,"newPassed":false,"retriesCount":1,"retriesStatusChange":false,"beforeStages":[],"testStage":{"status":"broken","statusMessage":"selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_TIMED_OUT\n  (Session info: headless chrome=108.0.5359.94)\n\n","statusTrace":"  File \"/opt/hostedtoolcache/Python/3.9.15/x64/lib/python3.9/site-packages/behave/model.py\", line 1812, in run\n    match.run(runner.context)\n  File \"/opt/hostedtoolcache/Python/3.9.15/x64/lib/python3.9/site-packages/behave/matchers.py\", line 97, in run\n    self.func(context, *args, **kwargs)\n  File \"features/steps/basic_steps.py\", line 86, in open_page\n    open_url(context, page_name)\n  File \"features/steps/basic_steps.py\", line 80, in open_url\n    context.driver.get(url) if url.startswith('http') else context.driver.get(f'https://{url}')\n  File \"/opt/hostedtoolcache/Python/3.9.15/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py\", line 333, in get\n    self.execute(Command.GET, {'url': url})\n  File \"/opt/hostedtoolcache/Python/3.9.15/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"/opt/hostedtoolcache/Python/3.9.15/x64/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n","steps":[{"name":"Given open a1-valves.com page","time":{"start":1671072142866,"stop":1671072274687,"duration":131821},"status":"broken","statusMessage":"selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_TIMED_OUT\n  (Session info: headless chrome=108.0.5359.94)\n\n","statusTrace":"  File \"/opt/hostedtoolcache/Python/3.9.15/x64/lib/python3.9/site-packages/behave/model.py\", line 1812, in run\n    match.run(runner.context)\n  File \"/opt/hostedtoolcache/Python/3.9.15/x64/lib/python3.9/site-packages/behave/matchers.py\", line 97, in run\n    self.func(context, *args, **kwargs)\n  File \"features/steps/basic_steps.py\", line 86, in open_page\n    open_url(context, page_name)\n  File \"features/steps/basic_steps.py\", line 80, in open_url\n    context.driver.get(url) if url.startswith('http') else context.driver.get(f'https://{url}')\n  File \"/opt/hostedtoolcache/Python/3.9.15/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py\", line 333, in get\n    self.execute(Command.GET, {'url': url})\n  File \"/opt/hostedtoolcache/Python/3.9.15/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"/opt/hostedtoolcache/Python/3.9.15/x64/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n","steps":[],"attachments":[{"uid":"957fa8592aec4ba1","name":"screenshot","source":"957fa8592aec4ba1.png","type":"image/png","size":10592}],"parameters":[],"stepsCount":0,"attachmentsCount":1,"shouldDisplayMessage":true,"hasContent":true},{"name":"When click on order call button in \"top menu section\"","time":{"start":1671072274693,"stop":1671072405256,"duration":130563},"status":"broken","statusMessage":"selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_TIMED_OUT\n  (Session info: headless chrome=108.0.5359.94)\n\n","statusTrace":"  File \"/opt/hostedtoolcache/Python/3.9.15/x64/lib/python3.9/site-packages/behave/model.py\", line 1812, in run\n    match.run(runner.context)\n  File \"/opt/hostedtoolcache/Python/3.9.15/x64/lib/python3.9/site-packages/behave/matchers.py\", line 97, in run\n    self.func(context, *args, **kwargs)\n  File \"features/steps/basic_steps.py\", line 86, in open_page\n    open_url(context, page_name)\n  File \"features/steps/basic_steps.py\", line 80, in open_url\n    context.driver.get(url) if url.startswith('http') else context.driver.get(f'https://{url}')\n  File \"/opt/hostedtoolcache/Python/3.9.15/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py\", line 333, in get\n    self.execute(Command.GET, {'url': url})\n  File \"/opt/hostedtoolcache/Python/3.9.15/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"/opt/hostedtoolcache/Python/3.9.15/x64/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n","steps":[],"attachments":[{"uid":"2b65d177159dc6ba","name":"screenshot","source":"2b65d177159dc6ba.png","type":"image/png","size":10592}],"parameters":[],"stepsCount":0,"attachmentsCount":1,"shouldDisplayMessage":true,"hasContent":true},{"name":"When enter \"generated_test_automation_email_call_a1\" in name field in \"request call section\"","time":{"start":1671072405256,"stop":1671072405256,"duration":0},"status":"skipped","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false},{"name":"When enter \"+70000000000\" in phone field in \"request call section\"","time":{"start":1671072405256,"stop":1671072405256,"duration":0},"status":"skipped","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false},{"name":"When click on send button in \"request call section\"","time":{"start":1671072405256,"stop":1671072405256,"duration":0},"status":"skipped","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false},{"name":"Then email with \"generated_test_automation_email_call_a1\" contains \"Телефон : +70000000000\" in 900 sec","time":{"start":1671072405256,"stop":1671072405256,"duration":0},"status":"skipped","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false},{"name":"Given open a1-valves.com page","time":{"start":1671072405256,"stop":1671072405256,"duration":0},"status":"broken","statusMessage":"selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_TIMED_OUT\n  (Session info: headless chrome=108.0.5359.94)\n\n","statusTrace":"  File \"/opt/hostedtoolcache/Python/3.9.15/x64/lib/python3.9/site-packages/behave/model.py\", line 1812, in run\n    match.run(runner.context)\n  File \"/opt/hostedtoolcache/Python/3.9.15/x64/lib/python3.9/site-packages/behave/matchers.py\", line 97, in run\n    self.func(context, *args, **kwargs)\n  File \"features/steps/basic_steps.py\", line 86, in open_page\n    open_url(context, page_name)\n  File \"features/steps/basic_steps.py\", line 80, in open_url\n    context.driver.get(url) if url.startswith('http') else context.driver.get(f'https://{url}')\n  File \"/opt/hostedtoolcache/Python/3.9.15/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py\", line 333, in get\n    self.execute(Command.GET, {'url': url})\n  File \"/opt/hostedtoolcache/Python/3.9.15/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"/opt/hostedtoolcache/Python/3.9.15/x64/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":true,"hasContent":true},{"name":"When click on order call button in \"top menu section\"","time":{"start":1671072405256,"stop":1671072405256,"duration":0},"status":"skipped","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false},{"name":"When enter \"generated_test_automation_email_call_a1\" in name field in \"request call section\"","time":{"start":1671072405256,"stop":1671072405256,"duration":0},"status":"skipped","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false},{"name":"When enter \"+70000000000\" in phone field in \"request call section\"","time":{"start":1671072405256,"stop":1671072405256,"duration":0},"status":"skipped","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false},{"name":"When click on send button in \"request call section\"","time":{"start":1671072405256,"stop":1671072405256,"duration":0},"status":"skipped","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false},{"name":"Then email with \"generated_test_automation_email_call_a1\" contains \"Телефон : +70000000000\" in 900 sec","time":{"start":1671072405256,"stop":1671072405256,"duration":0},"status":"skipped","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false}],"attachments":[],"parameters":[],"stepsCount":12,"attachmentsCount":2,"shouldDisplayMessage":false,"hasContent":true},"afterStages":[],"labels":[{"name":"severity","value":"normal"},{"name":"tag","value":"regression"},{"name":"feature","value":"Проверка сайта a1-valves.com"},{"name":"framework","value":"behave"},{"name":"language","value":"cpython3"},{"name":"resultFormat","value":"allure2"}],"parameters":[{"name":"section","value":"top menu section"}],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[{"uid":"5ad56a35f463cf3e","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=52509): Max retries exceeded with url: /session/7d62b791e5f18b7197021e3ff11da060/screenshot (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x113791570>: Failed to establish a new connection: [Errno 61] Connection refused'))\n","time":{"start":1667846550836,"stop":1667846576379,"duration":25543}}],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"history":{"statistic":{"failed":0,"broken":2,"skipped":0,"passed":14,"unknown":0,"total":16},"items":[{"uid":"49dad5c727fe8554","reportUrl":"https://automation-emk.github.io/popup-automation/65//#testresult/49dad5c727fe8554","status":"passed","time":{"start":1670985798139,"stop":1670985810040,"duration":11901}},{"uid":"ccfa156129bfc52c","reportUrl":"https://automation-emk.github.io/popup-automation/64//#testresult/ccfa156129bfc52c","status":"passed","time":{"start":1670899562630,"stop":1670899664720,"duration":102090}},{"uid":"8c5465e10d91c3cb","reportUrl":"https://automation-emk.github.io/popup-automation/63//#testresult/8c5465e10d91c3cb","status":"passed","time":{"start":1670813032617,"stop":1670813136540,"duration":103923}},{"uid":"c5153e1911246369","reportUrl":"https://automation-emk.github.io/popup-automation/62//#testresult/c5153e1911246369","status":"passed","time":{"start":1670726664372,"stop":1670726677804,"duration":13432}},{"uid":"9db6c7f321d913c2","reportUrl":"https://automation-emk.github.io/popup-automation/61//#testresult/9db6c7f321d913c2","status":"passed","time":{"start":1670639707149,"stop":1670639990138,"duration":282989}},{"uid":"675f8ff23392759f","reportUrl":"https://automation-emk.github.io/popup-automation/60//#testresult/675f8ff23392759f","status":"passed","time":{"start":1670553604066,"stop":1670553615110,"duration":11044}},{"uid":"f0c3e1abf3c26ed8","reportUrl":"https://automation-emk.github.io/popup-automation/59//#testresult/f0c3e1abf3c26ed8","status":"passed","time":{"start":1670468472875,"stop":1670468483601,"duration":10726}},{"uid":"5ce56f839e3dfb9f","reportUrl":"https://automation-emk.github.io/popup-automation/58//#testresult/5ce56f839e3dfb9f","status":"passed","time":{"start":1670382397128,"stop":1670382408911,"duration":11783}},{"uid":"41c2caaf75882069","reportUrl":"https://automation-emk.github.io/popup-automation/57//#testresult/41c2caaf75882069","status":"passed","time":{"start":1670295528596,"stop":1670295540889,"duration":12293}},{"uid":"32675eea12b26529","reportUrl":"https://automation-emk.github.io/popup-automation/56//#testresult/32675eea12b26529","status":"passed","time":{"start":1670209098712,"stop":1670209109519,"duration":10807}},{"uid":"1865bfb30c293ce2","reportUrl":"https://automation-emk.github.io/popup-automation/55//#testresult/1865bfb30c293ce2","status":"passed","time":{"start":1670122778242,"stop":1670122789962,"duration":11720}},{"uid":"38db8f95cc6876fb","reportUrl":"https://automation-emk.github.io/popup-automation/54//#testresult/38db8f95cc6876fb","status":"passed","time":{"start":1670061186386,"stop":1670061199093,"duration":12707}},{"uid":"4c902da7812d8a91","reportUrl":"https://automation-emk.github.io/popup-automation/53//#testresult/4c902da7812d8a91","status":"passed","time":{"start":1670060676520,"stop":1670060689868,"duration":13348}},{"uid":"85a967a575d1a667","reportUrl":"https://automation-emk.github.io/popup-automation/52//#testresult/85a967a575d1a667","status":"passed","time":{"start":1670059039080,"stop":1670059052921,"duration":13841}},{"uid":"a899e0c04541795","reportUrl":"https://automation-emk.github.io/popup-automation/50//#testresult/a899e0c04541795","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=52509): Max retries exceeded with url: /session/7d62b791e5f18b7197021e3ff11da060/screenshot (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x113791570>: Failed to establish a new connection: [Errno 61] Connection refused'))\n","time":{"start":1667846550836,"stop":1667846576379,"duration":25543}}]},"tags":["regression"]},"source":"92bd690e5a51d28b.json","parameterValues":["top menu section"]}